# Generated by Django 6.0.2 on 2026-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'ordering': ['display_order']},
        ),
        migrations.RenameField(
            model_name='whychooseus',
            old_name='order',
            new_name='display_order',
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='why_choose_us/'),
        ),
    ]
