# Generated by Django 6.0.2 on 2026-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='about/')),
                ('hero_subtitle', models.TextField()),
                ('why_description', models.TextField()),
                ('why_image', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
