# Generated by Django 6.0.2 on 2026-02-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
